name: dask-micro-2021
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh
  - dask=2021.2.0
  - distributed=2021.2.0
  - dask-sql=0.3.2
  - jupyterlab
  - nodejs
  - tornado
  - pip
  - matplotlib
  - dask_labextension

