name: dask-micro-2021
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh
  - dask
  - dask-sql=0.3.2
  - jupyterlab
  - nodejs
  - tornado
  - pip
  - matplotlib
  - dask_labextension  
